(() => {
  const root=document.getElementById('trade-lab'); if(!root)return;
  const priceCanvas=document.getElementById('trade-chart'), equityCanvas=document.getElementById('equity-chart');
  const pctx=priceCanvas.getContext('2d'), ectx=equityCanvas.getContext('2d');
  const shortInput=document.getElementById('short-window'), longInput=document.getElementById('long-window');
  const shortVal=document.getElementById('short-window-value'), longVal=document.getElementById('long-window-value');
  const capitalSel=document.getElementById('trade-capital'), feeSel=document.getElementById('trade-fee');
  const runBtn=document.getElementById('trade-run'), stepBtn=document.getElementById('trade-step'), resetBtn=document.getElementById('trade-reset');
  const status=document.getElementById('trade-status');
  const dateEl=document.getElementById('trade-date'), actionEl=document.getElementById('trade-action'), eqEl=document.getElementById('trade-equity'), retEl=document.getElementById('trade-return'), benchEl=document.getElementById('trade-benchmark'), countEl=document.getElementById('trade-count'), ddEl=document.getElementById('trade-drawdown');
  let raw=[], rows=[], idx=-1, running=false, timer=null, state=null;
  const css=n=>getComputedStyle(document.documentElement).getPropertyValue(n).trim();
  const money=v=>Number.isFinite(v)?'$'+v.toLocaleString('en-US',{maximumFractionDigits:0}):'—';
  const pct=v=>Number.isFinite(v)?(v>=0?'+':'')+v.toFixed(1)+'%':'—';
  const month=d=>d.toLocaleDateString('en-US',{month:'short',year:'numeric'});
  function parseCSV(text){const lines=text.trim().split(/\r?\n/);lines.shift();return lines.map(l=>{const [d,p]=l.split(',');return{date:new Date(d+'T00:00:00'),price:+p};}).filter(r=>r.date>=new Date('2008-01-01T00:00:00'));}
  function sma(data,i,w){if(i<w-1)return NaN;let s=0;for(let j=i-w+1;j<=i;j++)s+=data[j].price;return s/w;}
  function configure(){let s=+shortInput.value,l=+longInput.value;if(s>=l){l=Math.min(24,s+2);longInput.value=l;}shortVal.textContent=s;longVal.textContent=l;rows=raw.map((r,i)=>({...r,short:sma(raw,i,s),long:sma(raw,i,l)})); idx=-1; running=false; clearTimeout(timer); state={cash:+capitalSel.value,shares:0,capital:+capitalSel.value,fee:+feeSel.value,trades:[],equity:[],benchmark:[],peak:+capitalSel.value,maxDD:0,prevAbove:null}; runBtn.textContent='▶ Run backtest'; updateUI(null,'—'); drawAll(); status.textContent='Ready. Press Run backtest or Step one month.';}
  function updateUI(row,action){dateEl.textContent=row?month(row.date):'—'; actionEl.textContent=action; actionEl.className=action==='BUY'?'metric-good':action==='SELL'?'metric-bad':''; const eq=state&&state.equity.length?state.equity[state.equity.length-1]:state?.capital; eqEl.textContent=money(eq); retEl.textContent=state&&eq? pct((eq/state.capital-1)*100):'—'; const b=state&&state.benchmark.length?state.benchmark[state.benchmark.length-1]:state?.capital; benchEl.textContent=money(b); countEl.textContent=state?state.trades.length:'0'; ddEl.textContent=state?'Max drawdown '+pct(state.maxDD*100):'Max drawdown —';}
  function step(auto=false){if(idx>=rows.length-1){running=false;runBtn.textContent='↻ Replay';status.textContent='Backtest complete. Change a parameter to rerun the strategy.';return;}idx++;const r=rows[idx];let action='HOLD';const above=Number.isFinite(r.short)&&Number.isFinite(r.long)?r.short>r.long:null;
    if(above!==null&&state.prevAbove!==null){if(above&&!state.prevAbove&&state.shares===0){state.shares=(state.cash*(1-state.fee))/r.price;state.cash=0;action='BUY';state.trades.push({i:idx,type:'BUY',price:r.price});}else if(!above&&state.prevAbove&&state.shares>0){state.cash=state.shares*r.price*(1-state.fee);state.shares=0;action='SELL';state.trades.push({i:idx,type:'SELL',price:r.price});}}
    if(above!==null)state.prevAbove=above;const equity=state.cash+state.shares*r.price;state.equity.push(equity);state.peak=Math.max(state.peak,equity);state.maxDD=Math.min(state.maxDD,equity/state.peak-1);const first=rows[0].price;state.benchmark.push(state.capital*(r.price/first)); updateUI(r,action); status.textContent=month(r.date)+' · '+action+' · AAPL $'+r.price.toFixed(2)+(Number.isFinite(r.short)?' · SMA '+shortInput.value+' '+r.short.toFixed(2)+' / '+longInput.value+' '+r.long.toFixed(2):' · warming up moving averages'); drawAll(); if(auto&&running)timer=setTimeout(()=>step(true),145);}
  function fitCanvas(c,ctx){const rect=c.getBoundingClientRect(),dpr=Math.max(1,Math.min(2,devicePixelRatio||1));c.width=Math.round(rect.width*dpr);c.height=Math.round(rect.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);}
  function axes(ctx,c,min,max,pad){const w=c.clientWidth,h=c.clientHeight;ctx.strokeStyle='rgba(255,255,255,.07)';ctx.lineWidth=1;ctx.font='10px system-ui';ctx.fillStyle='rgba(220,225,235,.55)';for(let j=0;j<5;j++){const y=pad.t+j*(h-pad.t-pad.b)/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillText((max-j*(max-min)/4).toFixed(0),6,y+3);}return{w,h,x:i=>pad.l+(i/(Math.max(1,rows.length-1)))*(w-pad.l-pad.r),y:v=>pad.t+(max-v)/(max-min||1)*(h-pad.t-pad.b)};}
  function drawPrice(){const c=priceCanvas,ctx=pctx,w=c.clientWidth,h=c.clientHeight;ctx.clearRect(0,0,w,h);if(!rows.length)return;const vals=rows.flatMap(r=>[r.price,r.short,r.long]).filter(Number.isFinite),min0=Math.min(...vals),max0=Math.max(...vals),ex=(max0-min0)*.08||1;const pad={l:48,r:14,t:20,b:32},a=axes(ctx,c,min0-ex,max0+ex,pad);const upto=Math.max(idx,0);
    function line(key,color,width){ctx.beginPath();let started=false;for(let i=0;i<=upto&&i<rows.length;i++){const v=rows[i][key];if(!Number.isFinite(v))continue;const xx=a.x(i),yy=a.y(v);if(!started){ctx.moveTo(xx,yy);started=true;}else ctx.lineTo(xx,yy);}ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
    if(idx>=0){line('price','#f5f7fb',2);line('short',css('--accent-2')||'#9ecbff',1.8);line('long','#f0b46f',1.8);state.trades.forEach(t=>{const xx=a.x(t.i),yy=a.y(rows[t.i].price);ctx.beginPath();ctx.arc(xx,yy,5,0,Math.PI*2);ctx.fillStyle=t.type==='BUY'?'#74d8a3':'#ff8d8d';ctx.fill();ctx.strokeStyle='#0b0c0f';ctx.lineWidth=2;ctx.stroke();});const xx=a.x(idx);ctx.strokeStyle='rgba(255,255,255,.22)';ctx.beginPath();ctx.moveTo(xx,pad.t);ctx.lineTo(xx,h-pad.b);ctx.stroke();}
    for(let j=0;j<5;j++){const i=Math.round(j*(rows.length-1)/4);ctx.fillStyle='rgba(220,225,235,.48)';ctx.fillText(String(rows[i].date.getFullYear()),a.x(i)-11,h-9);}}
  function drawEquity(){const c=equityCanvas,ctx=ectx,w=c.clientWidth,h=c.clientHeight;ctx.clearRect(0,0,w,h);if(!state||!state.equity.length)return;const vals=[...state.equity,...state.benchmark],min0=Math.min(...vals),max0=Math.max(...vals),ex=(max0-min0)*.08||1;const pad={l:48,r:14,t:15,b:24};const count=state.equity.length;function x(i){return pad.l+(i/(Math.max(1,rows.length-1)))*(w-pad.l-pad.r)}function y(v){return pad.t+(max0+ex-v)/(max0+ex-(min0-ex))*(h-pad.t-pad.b)}ctx.strokeStyle='rgba(255,255,255,.07)';for(let j=0;j<4;j++){const yy=pad.t+j*(h-pad.t-pad.b)/3;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();}function line(arr,color,width){ctx.beginPath();arr.forEach((v,i)=>{const xx=x(i),yy=y(v);i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)});ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}line(state.benchmark,'rgba(245,247,251,.38)',1.5);line(state.equity,css('--accent-2')||'#9ecbff',2.4);}
  function drawAll(){drawPrice();drawEquity();}
  function resize(){fitCanvas(priceCanvas,pctx);fitCanvas(equityCanvas,ectx);drawAll();}
  [shortInput,longInput,capitalSel,feeSel].forEach(el=>el.addEventListener('input',configure)); runBtn.addEventListener('click',()=>{if(running){running=false;clearTimeout(timer);runBtn.textContent='▶ Resume';return;}if(idx>=rows.length-1)configure();running=true;runBtn.textContent='Ⅱ Pause';step(true);}); stepBtn.addEventListener('click',()=>{running=false;clearTimeout(timer);runBtn.textContent='▶ Run backtest';step(false);});resetBtn.addEventListener('click',configure);
  fetch(root.dataset.csv).then(r=>{if(!r.ok)throw new Error();return r.text();}).then(t=>{raw=parseCSV(t);configure();resize();}).catch(()=>status.textContent='Could not load the local AAPL history. Check the projects folder was uploaded to GitHub.'); new ResizeObserver(resize).observe(root);
})();
